// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsAPI.Database;

#nullable disable

namespace Products.API.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    [Migration("20240909094027_AddMaxLengthToColumns")]
    partial class AddMaxLengthToColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductsAPI.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUri")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImageUri = "https://example.com/images/product1.jpg",
                            Name = "Bike",
                            Price = 111.63m
                        },
                        new
                        {
                            Id = 2,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImageUri = "https://example.com/images/product2.jpg",
                            Name = "Cheese",
                            Price = 404.76m
                        },
                        new
                        {
                            Id = 3,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImageUri = "https://example.com/images/product3.jpg",
                            Name = "Gloves",
                            Price = 697.88m
                        },
                        new
                        {
                            Id = 4,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImageUri = "https://example.com/images/product4.jpg",
                            Name = "Bacon",
                            Price = 991.01m
                        },
                        new
                        {
                            Id = 5,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImageUri = "https://example.com/images/product5.jpg",
                            Name = "Pants",
                            Price = 285.13m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImageUri = "https://example.com/images/product6.jpg",
                            Name = "Pizza",
                            Price = 578.26m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImageUri = "https://example.com/images/product7.jpg",
                            Name = "Shirt",
                            Price = 871.38m
                        },
                        new
                        {
                            Id = 8,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImageUri = "https://example.com/images/product8.jpg",
                            Name = "Salad",
                            Price = 165.51m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImageUri = "https://example.com/images/product9.jpg",
                            Name = "Table",
                            Price = 458.63m
                        },
                        new
                        {
                            Id = 10,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImageUri = "https://example.com/images/product10.jpg",
                            Name = "Sausages",
                            Price = 751.76m
                        },
                        new
                        {
                            Id = 11,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImageUri = "https://example.com/images/product11.jpg",
                            Name = "Shoes",
                            Price = 45.89m
                        },
                        new
                        {
                            Id = 12,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImageUri = "https://example.com/images/product12.jpg",
                            Name = "Chips",
                            Price = 339.01m
                        },
                        new
                        {
                            Id = 13,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImageUri = "https://example.com/images/product13.jpg",
                            Name = "Hat",
                            Price = 632.14m
                        },
                        new
                        {
                            Id = 14,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImageUri = "https://example.com/images/product14.jpg",
                            Name = "Chair",
                            Price = 925.26m
                        },
                        new
                        {
                            Id = 15,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImageUri = "https://example.com/images/product15.jpg",
                            Name = "Towels",
                            Price = 219.39m
                        },
                        new
                        {
                            Id = 16,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImageUri = "https://example.com/images/product16.jpg",
                            Name = "Computer",
                            Price = 512.51m
                        },
                        new
                        {
                            Id = 17,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImageUri = "https://example.com/images/product17.jpg",
                            Name = "Soap",
                            Price = 805.64m
                        },
                        new
                        {
                            Id = 18,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImageUri = "https://example.com/images/product18.jpg",
                            Name = "Keyboard",
                            Price = 99.76m
                        },
                        new
                        {
                            Id = 19,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImageUri = "https://example.com/images/product19.jpg",
                            Name = "Tuna",
                            Price = 392.89m
                        },
                        new
                        {
                            Id = 20,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImageUri = "https://example.com/images/product20.jpg",
                            Name = "Mouse",
                            Price = 686.01m
                        },
                        new
                        {
                            Id = 21,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImageUri = "https://example.com/images/product21.jpg",
                            Name = "Chicken",
                            Price = 979.14m
                        },
                        new
                        {
                            Id = 22,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImageUri = "https://example.com/images/product22.jpg",
                            Name = "Bike",
                            Price = 273.26m
                        },
                        new
                        {
                            Id = 23,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImageUri = "https://example.com/images/product23.jpg",
                            Name = "Fish",
                            Price = 566.39m
                        },
                        new
                        {
                            Id = 24,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImageUri = "https://example.com/images/product24.jpg",
                            Name = "Ball",
                            Price = 859.51m
                        },
                        new
                        {
                            Id = 25,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImageUri = "https://example.com/images/product25.jpg",
                            Name = "Cheese",
                            Price = 153.64m
                        },
                        new
                        {
                            Id = 26,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImageUri = "https://example.com/images/product26.jpg",
                            Name = "Gloves",
                            Price = 446.76m
                        },
                        new
                        {
                            Id = 27,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImageUri = "https://example.com/images/product27.jpg",
                            Name = "Bacon",
                            Price = 739.89m
                        },
                        new
                        {
                            Id = 28,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImageUri = "https://example.com/images/product28.jpg",
                            Name = "Pants",
                            Price = 34.01m
                        },
                        new
                        {
                            Id = 29,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImageUri = "https://example.com/images/product29.jpg",
                            Name = "Salad",
                            Price = 327.14m
                        },
                        new
                        {
                            Id = 30,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImageUri = "https://example.com/images/product30.jpg",
                            Name = "Shirt",
                            Price = 620.26m
                        },
                        new
                        {
                            Id = 31,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImageUri = "https://example.com/images/product31.jpg",
                            Name = "Sausages",
                            Price = 913.39m
                        },
                        new
                        {
                            Id = 32,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImageUri = "https://example.com/images/product32.jpg",
                            Name = "Table",
                            Price = 207.51m
                        },
                        new
                        {
                            Id = 33,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImageUri = "https://example.com/images/product33.jpg",
                            Name = "Chips",
                            Price = 500.64m
                        },
                        new
                        {
                            Id = 34,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImageUri = "https://example.com/images/product34.jpg",
                            Name = "Shoes",
                            Price = 793.76m
                        },
                        new
                        {
                            Id = 35,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImageUri = "https://example.com/images/product35.jpg",
                            Name = "Chair",
                            Price = 87.89m
                        },
                        new
                        {
                            Id = 36,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImageUri = "https://example.com/images/product36.jpg",
                            Name = "Hat",
                            Price = 381.02m
                        },
                        new
                        {
                            Id = 37,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImageUri = "https://example.com/images/product37.jpg",
                            Name = "Car",
                            Price = 674.14m
                        },
                        new
                        {
                            Id = 38,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImageUri = "https://example.com/images/product38.jpg",
                            Name = "Towels",
                            Price = 967.27m
                        },
                        new
                        {
                            Id = 39,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImageUri = "https://example.com/images/product39.jpg",
                            Name = "Computer",
                            Price = 261.39m
                        },
                        new
                        {
                            Id = 40,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImageUri = "https://example.com/images/product40.jpg",
                            Name = "Soap",
                            Price = 554.52m
                        },
                        new
                        {
                            Id = 41,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImageUri = "https://example.com/images/product41.jpg",
                            Name = "Keyboard",
                            Price = 847.64m
                        },
                        new
                        {
                            Id = 42,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImageUri = "https://example.com/images/product42.jpg",
                            Name = "Chicken",
                            Price = 141.77m
                        },
                        new
                        {
                            Id = 43,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImageUri = "https://example.com/images/product43.jpg",
                            Name = "Mouse",
                            Price = 434.89m
                        },
                        new
                        {
                            Id = 44,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImageUri = "https://example.com/images/product44.jpg",
                            Name = "Fish",
                            Price = 728.02m
                        },
                        new
                        {
                            Id = 45,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImageUri = "https://example.com/images/product45.jpg",
                            Name = "Bike",
                            Price = 22.14m
                        },
                        new
                        {
                            Id = 46,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImageUri = "https://example.com/images/product46.jpg",
                            Name = "Cheese",
                            Price = 315.27m
                        },
                        new
                        {
                            Id = 47,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImageUri = "https://example.com/images/product47.jpg",
                            Name = "Ball",
                            Price = 608.39m
                        },
                        new
                        {
                            Id = 48,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImageUri = "https://example.com/images/product48.jpg",
                            Name = "Bacon",
                            Price = 901.52m
                        },
                        new
                        {
                            Id = 49,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImageUri = "https://example.com/images/product49.jpg",
                            Name = "Gloves",
                            Price = 195.64m
                        },
                        new
                        {
                            Id = 50,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImageUri = "https://example.com/images/product50.jpg",
                            Name = "Pizza",
                            Price = 488.77m
                        },
                        new
                        {
                            Id = 51,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImageUri = "https://example.com/images/product51.jpg",
                            Name = "Pants",
                            Price = 781.89m
                        },
                        new
                        {
                            Id = 52,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImageUri = "https://example.com/images/product52.jpg",
                            Name = "Salad",
                            Price = 76.02m
                        },
                        new
                        {
                            Id = 53,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImageUri = "https://example.com/images/product53.jpg",
                            Name = "Shirt",
                            Price = 369.14m
                        },
                        new
                        {
                            Id = 54,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImageUri = "https://example.com/images/product54.jpg",
                            Name = "Sausages",
                            Price = 662.27m
                        },
                        new
                        {
                            Id = 55,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImageUri = "https://example.com/images/product55.jpg",
                            Name = "Shoes",
                            Price = 955.39m
                        },
                        new
                        {
                            Id = 56,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImageUri = "https://example.com/images/product56.jpg",
                            Name = "Chips",
                            Price = 249.52m
                        },
                        new
                        {
                            Id = 57,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImageUri = "https://example.com/images/product57.jpg",
                            Name = "Hat",
                            Price = 542.64m
                        },
                        new
                        {
                            Id = 58,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImageUri = "https://example.com/images/product58.jpg",
                            Name = "Chair",
                            Price = 835.77m
                        },
                        new
                        {
                            Id = 59,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImageUri = "https://example.com/images/product59.jpg",
                            Name = "Towels",
                            Price = 129.89m
                        },
                        new
                        {
                            Id = 60,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImageUri = "https://example.com/images/product60.jpg",
                            Name = "Car",
                            Price = 423.02m
                        },
                        new
                        {
                            Id = 61,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImageUri = "https://example.com/images/product61.jpg",
                            Name = "Soap",
                            Price = 716.15m
                        },
                        new
                        {
                            Id = 62,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImageUri = "https://example.com/images/product62.jpg",
                            Name = "Computer",
                            Price = 10.27m
                        },
                        new
                        {
                            Id = 63,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImageUri = "https://example.com/images/product63.jpg",
                            Name = "Tuna",
                            Price = 303.40m
                        },
                        new
                        {
                            Id = 64,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImageUri = "https://example.com/images/product64.jpg",
                            Name = "Keyboard",
                            Price = 596.52m
                        },
                        new
                        {
                            Id = 65,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImageUri = "https://example.com/images/product65.jpg",
                            Name = "Chicken",
                            Price = 889.65m
                        },
                        new
                        {
                            Id = 66,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImageUri = "https://example.com/images/product66.jpg",
                            Name = "Mouse",
                            Price = 183.77m
                        },
                        new
                        {
                            Id = 67,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImageUri = "https://example.com/images/product67.jpg",
                            Name = "Fish",
                            Price = 476.90m
                        },
                        new
                        {
                            Id = 68,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImageUri = "https://example.com/images/product68.jpg",
                            Name = "Ball",
                            Price = 770.02m
                        },
                        new
                        {
                            Id = 69,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImageUri = "https://example.com/images/product69.jpg",
                            Name = "Cheese",
                            Price = 64.15m
                        },
                        new
                        {
                            Id = 70,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImageUri = "https://example.com/images/product70.jpg",
                            Name = "Gloves",
                            Price = 357.27m
                        },
                        new
                        {
                            Id = 71,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImageUri = "https://example.com/images/product71.jpg",
                            Name = "Bacon",
                            Price = 650.40m
                        },
                        new
                        {
                            Id = 72,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImageUri = "https://example.com/images/product72.jpg",
                            Name = "Pants",
                            Price = 943.52m
                        },
                        new
                        {
                            Id = 73,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImageUri = "https://example.com/images/product73.jpg",
                            Name = "Pizza",
                            Price = 237.65m
                        },
                        new
                        {
                            Id = 74,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImageUri = "https://example.com/images/product74.jpg",
                            Name = "Shirt",
                            Price = 530.77m
                        },
                        new
                        {
                            Id = 75,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImageUri = "https://example.com/images/product75.jpg",
                            Name = "Salad",
                            Price = 823.90m
                        },
                        new
                        {
                            Id = 76,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImageUri = "https://example.com/images/product76.jpg",
                            Name = "Table",
                            Price = 118.02m
                        },
                        new
                        {
                            Id = 77,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ImageUri = "https://example.com/images/product77.jpg",
                            Name = "Sausages",
                            Price = 411.15m
                        },
                        new
                        {
                            Id = 78,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImageUri = "https://example.com/images/product78.jpg",
                            Name = "Shoes",
                            Price = 704.27m
                        },
                        new
                        {
                            Id = 79,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImageUri = "https://example.com/images/product79.jpg",
                            Name = "Chips",
                            Price = 997.40m
                        },
                        new
                        {
                            Id = 80,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImageUri = "https://example.com/images/product80.jpg",
                            Name = "Hat",
                            Price = 291.52m
                        },
                        new
                        {
                            Id = 81,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImageUri = "https://example.com/images/product81.jpg",
                            Name = "Car",
                            Price = 584.65m
                        },
                        new
                        {
                            Id = 82,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ImageUri = "https://example.com/images/product82.jpg",
                            Name = "Towels",
                            Price = 877.77m
                        },
                        new
                        {
                            Id = 83,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImageUri = "https://example.com/images/product83.jpg",
                            Name = "Computer",
                            Price = 171.90m
                        },
                        new
                        {
                            Id = 84,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImageUri = "https://example.com/images/product84.jpg",
                            Name = "Soap",
                            Price = 465.02m
                        },
                        new
                        {
                            Id = 85,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImageUri = "https://example.com/images/product85.jpg",
                            Name = "Keyboard",
                            Price = 758.15m
                        },
                        new
                        {
                            Id = 86,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImageUri = "https://example.com/images/product86.jpg",
                            Name = "Tuna",
                            Price = 52.28m
                        },
                        new
                        {
                            Id = 87,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImageUri = "https://example.com/images/product87.jpg",
                            Name = "Mouse",
                            Price = 345.40m
                        },
                        new
                        {
                            Id = 88,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImageUri = "https://example.com/images/product88.jpg",
                            Name = "Chicken",
                            Price = 638.53m
                        },
                        new
                        {
                            Id = 89,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImageUri = "https://example.com/images/product89.jpg",
                            Name = "Bike",
                            Price = 931.65m
                        },
                        new
                        {
                            Id = 90,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImageUri = "https://example.com/images/product90.jpg",
                            Name = "Fish",
                            Price = 225.78m
                        },
                        new
                        {
                            Id = 91,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ImageUri = "https://example.com/images/product91.jpg",
                            Name = "Ball",
                            Price = 518.90m
                        },
                        new
                        {
                            Id = 92,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            ImageUri = "https://example.com/images/product92.jpg",
                            Name = "Cheese",
                            Price = 812.03m
                        },
                        new
                        {
                            Id = 93,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ImageUri = "https://example.com/images/product93.jpg",
                            Name = "Gloves",
                            Price = 106.15m
                        },
                        new
                        {
                            Id = 94,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ImageUri = "https://example.com/images/product94.jpg",
                            Name = "Pizza",
                            Price = 399.28m
                        },
                        new
                        {
                            Id = 95,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ImageUri = "https://example.com/images/product95.jpg",
                            Name = "Pants",
                            Price = 692.40m
                        },
                        new
                        {
                            Id = 96,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ImageUri = "https://example.com/images/product96.jpg",
                            Name = "Salad",
                            Price = 985.53m
                        },
                        new
                        {
                            Id = 97,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ImageUri = "https://example.com/images/product97.jpg",
                            Name = "Shirt",
                            Price = 279.65m
                        },
                        new
                        {
                            Id = 98,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ImageUri = "https://example.com/images/product98.jpg",
                            Name = "Sausages",
                            Price = 572.78m
                        },
                        new
                        {
                            Id = 99,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ImageUri = "https://example.com/images/product99.jpg",
                            Name = "Table",
                            Price = 865.90m
                        },
                        new
                        {
                            Id = 100,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ImageUri = "https://example.com/images/product100.jpg",
                            Name = "Chips",
                            Price = 160.03m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
