version: '3.4'

services:
  db:
    container_name: docker-sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=BigPassword1!
    ports:
      - "1433:1433"